hub:
   environments:
       - name: "Firefox 5 on Windows 7"
         browser: "*firefox C:/Program Files/Mozilla Firefox/firefox.exe"
       - name: "Internet Explorer 8 on Windows 7"
         browser: "*iexplore"
